[project]
name = "safeway"
version = "1.0.0"
description = "SafeWay Routing API"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.0",
    "fastapi>=0.115.0",
    "uvicorn>=0.30.0",
    "torch>=2.4.0",
    "torchdiffeq>=0.2.4",
    "numpy>=1.26.0"
]

[tool.vercel]
entrypoint = "backend.api:app"
